name: CI/CD → Azure Functions

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Archive function app
        run: |
          # zip up everything except your virtual-env and caches
          zip -r function.zip . -x ".venv/*" "__pycache__/*"
          # verify it exists
          echo "Contents of workspace:"
          ls -lah
          echo "ZIP file:"
          ls -lah function.zip


      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy to Azure Functions
        run: |
          az functionapp deployment source config-zip \
            --resource-group PdfPipelineRG \
            --name TrinityPdfPipeline \
            --src function.zip
