name: Build & Deploy Azure Function

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Create zip package
        run: |
          zip -r function.zip host.json function_app.py requirements.txt

      - name: Deploy to Azure Functions
        run: |
          az functionapp deployment source config-zip \
            --name TrinityPdfPipeline \
            --resource-group PdfPipelineRG \
            --src function.zip
